### ISSUE TITLE
Delete 2 unneeded files

### ISSUE THREAD

**Issue by VTskier** [LSVermont/docassemble-VTFamilyCourtInfoSheet#22]
Mia: Could you delete these two unneeded files, which I crossed out with an X?

![image](https://github.com/LSVermont/docassemble-VTFamilyCourtInfoSheet/assets/104463248/c4a0d724-3bc6-48dc-bc3a-154a1523653c)

**Comment by miabonardi** [comment]
Should be all set now! 

Make sure to create a new project in your playground so you dont commit these files on accident again. 

Also, because I know you like to learn how to do these things, here's how you can remove the files in github in the future: 

![Screen Shot 2024-02-21 at 12 23 08 PM](https://github.com/LSVermont/docassemble-VTFamilyCourtInfoSheet/assets/65858862/9b895d71-ca69-47b3-9790-d45b44530280)
![Screen Shot 2024-02-21 at 12 24 57 PM](https://github.com/LSVermont/docassemble-VTFamilyCourtInfoSheet/assets/65858862/6a108504-97c9-47c0-862d-0a5268e77e19)
